version: '2'
services:
  redis:
    image: redis:alpine
  redis_daphne:
    image: channels-redis-test
    build:
      context: .
      dockerfile: Dockerfile.redis
    command: daphne -b 0.0.0.0 -p 80 testproject.asgi.redis:channel_layer
    volumes:
      - .:/srv/channels/testproject/
    ports:
      - "80:80"
    depends_on:
      - redis
  redis_worker:
    image: channels-redis-test
    build:
      context: .
      dockerfile: Dockerfile.redis
    command: python manage.py runworker --settings=testproject.settings.channels_redis
    volumes:
      - .:/srv/channels/testproject/
    depends_on:
      - redis
